apiVersion: v1
kind: ConfigMap
metadata:
  name: labfactory-config
  namespace: labfactory-dev
data:
  NODE_ENV: "development"
  PORT: "3000"
  LOG_LEVEL: "debug"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  SESSION_COOKIE_SECURE: "false"
  TRUST_PROXY: "true"
  K8S_NAMESPACE: "labfactory-dev"
  K8S_SERVICE_ACCOUNT: "labfactory-runner-job"
  TERRAFORM_RUNNER_IMAGE: "hurtlinb/labfactory:worker-1.1.3"
  ANSIBLE_RUNNER_IMAGE: "hurtlinb/labfactory:worker-1.1.3"
  LAUNCHER_POLL_INTERVAL_MS: "5000"
  LAUNCHER_JOB_TIMEOUT_MS: "1800000"
  SCHEDULER_QUEUE_NAME: "execution-scheduler"
  LAUNCHER_QUEUE_NAME: "execution-launcher"
  TF_IN_AUTOMATION: "1"
  PROXMOX_API_URL: "https://10.1.2.101:8006/api2/json"
  PROXMOX_NODE: "pve1"
  PROXMOX_TLS_INSECURE: "true"
  OIDC_ISSUER_URL: "https://auth.app.emfnet.ch/realms/emf"
  OIDC_CLIENT_ID: "labfactory-dev"
  OIDC_SCOPES: "openid profile email"
  OIDC_REDIRECT_URI: "https://labfactory-dev.emfnet.ch/auth/callback"
  OIDC_POST_LOGOUT_REDIRECT_URI: "https://labfactory-dev.emfnet.ch"
