apiVersion: apps/v1
kind: Deployment
metadata:
  name: labfactory-ansible-worker
  namespace: labfactory-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labfactory-ansible-worker
  template:
    metadata:
      labels:
        app: labfactory-ansible-worker
    spec:
      imagePullSecrets:
        - name: dockerhub-pull-secret
      containers:
        - name: ansible-worker
          image: hurtlinb/labfactory:worker-1.3.0
          imagePullPolicy: Always
          command: ["npm", "run", "ansible-worker"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: labfactory-secrets
                  key: database-url
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: labfactory-secrets
                  key: redis-password
            - name: PROXMOX_API_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: labfactory-secrets
                  key: proxmox-token-id
            - name: PROXMOX_API_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: labfactory-secrets
                  key: proxmox-token-secret
          envFrom:
            - configMapRef:
                name: labfactory-config
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
