all:
  children:
    windows_timezone_targets:
      hosts:
        vm_1:
          ansible_host: 10.10.50.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-01-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_2:
          ansible_host: 10.10.51.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-02-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_3:
          ansible_host: 10.10.52.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-03-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_4:
          ansible_host: 10.10.53.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-04-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_5:
          ansible_host: 10.10.54.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-05-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_6:
          ansible_host: 10.10.55.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-06-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_7:
          ansible_host: 10.10.56.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-07-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_8:
          ansible_host: 10.10.57.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-08-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_9:
          ansible_host: 10.10.58.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-09-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_10:
          ansible_host: 10.10.59.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-10-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_11:
          ansible_host: 10.10.60.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-11-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_12:
          ansible_host: 10.10.61.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-12-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_13:
          ansible_host: 10.10.62.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-13-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_14:
          ansible_host: 10.10.63.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-14-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_15:
          ansible_host: 10.10.64.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-15-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_16:
          ansible_host: 10.10.65.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-16-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_17:
          ansible_host: 10.10.66.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-17-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_18:
          ansible_host: 10.10.67.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-18-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_19:
          ansible_host: 10.10.68.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-19-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_20:
          ansible_host: 10.10.69.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-20-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_21:
          ansible_host: 10.10.70.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-21-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
        vm_22:
          ansible_host: 10.10.71.63
          ansible_user: "Administrator"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "122-bhu-test-22-srv1"
          target_timezone: "W. Europe Standard Time"
          target_hostname: "SRV1"
