all:
  children:
    windows_timezone_targets:
      hosts:
        vm_1:
          ansible_host: 10.19.60.25
          ansible_user: "Administrateur"
          ansible_password: "Emf12345"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_scheme: https
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          target_vm_name: "win11-test-01-testtest"
          target_timezone: "null"
          target_hostname: "testtest"
