apiVersion: v1
kind: ServiceAccount
metadata:
  name: labfactory-api

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: labfactory-scheduler

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: labfactory-launcher

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: labfactory-runner-job

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: labfactory-launcher
rules:
  - apiGroups: ['batch']
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups: ['']
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: labfactory-launcher
subjects:
  - kind: ServiceAccount
    name: labfactory-launcher
roleRef:
  kind: Role
  name: labfactory-launcher
  apiGroup: rbac.authorization.k8s.io
